// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsF-tEVHiGpH3ud4gsRO_w1-IEIo_aswA',
    appId: '1:734273228381:web:4d869b79c9ebb7d5be47b4',
    messagingSenderId: '734273228381',
    projectId: 'fir-flutter-codelab-278c7',
    authDomain: 'fir-flutter-codelab-278c7.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-278c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUBBqwgSLDC5cqxAzAZMUm6YPXjAYfuVM',
    appId: '1:734273228381:android:9a8a51f6428506b5be47b4',
    messagingSenderId: '734273228381',
    projectId: 'fir-flutter-codelab-278c7',
    storageBucket: 'fir-flutter-codelab-278c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBimK8ywUfq_OE7icSvIq93WSkUsBpegYk',
    appId: '1:734273228381:ios:cb8359ad715212aabe47b4',
    messagingSenderId: '734273228381',
    projectId: 'fir-flutter-codelab-278c7',
    storageBucket: 'fir-flutter-codelab-278c7.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBimK8ywUfq_OE7icSvIq93WSkUsBpegYk',
    appId: '1:734273228381:ios:cb8359ad715212aabe47b4',
    messagingSenderId: '734273228381',
    projectId: 'fir-flutter-codelab-278c7',
    storageBucket: 'fir-flutter-codelab-278c7.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
